### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [meganrofl/prj-rev-bwfs-tea-cozy#5]
Summary Grade: Exceeds Expectations

Good job with your code! I really liked the way you clearly organized your html code with whitespace and indentations. It makes your code really easy to navigate and read. Also, I really like the way you used classes and ids to group your sections together. As your code grows in size, this will help organize and manage your website. Excellent start to the Ready program!

I included a few notes in both the html and css files for you to think more critically about. You can find these comments in the issues tab of your github. The most important thing is to add mobile resizing. I know that it can be tedious, but you should try to add mobile resizing so you control how your website looks even on different mobile screens. Some suggestions would be to decrease the size of the images when the screen size decreases or rearrange the layout of the text and images so you don’t have to scroll horizontally to read everything. Finally, you saved the images locally but you still reference online images. Make to save them locally.

**Comment by meganrofl** [comment]
Thank you so much for your positive feedback and highlighting great recommendations to improve on, especially towards commenting the CSS file, mobile resizing, and the local images used. 

I will be sure to go back to add the CSS comments so in the future the code will be more intuitive when reviewing.
I was concerned using the local images, previously I had tried but they were not visible on the last project to the reviewer on GitHub and hoped using online images would be safer for the repository. 
I will also revisit the mobile resizing
(I'm bad and haven't completed that lesson yet on Codecademy, oops!) BUT I'm excited to learn those mobile skills to reach further audiences :)
Thank you again for giving constructive feedback and helping me grow!
